### ISSUE TITLE
About problems to create PR for

### ISSUE THREAD

**Issue by dhairyaostwal** [ISTE-VIT/The-Algo-Companion#15]
@zainanizar and Maintainers Heartiest Greetings!

I have a doubt about contributing since there are topics but not issues about what problems to contribute. 

1. Can I solve any famous problems and list down their solution as PR or would you be listing issues. 
2. Also would you guys accept Java alongside C++ and C.

**Comment by zainanizar** [comment]
Greetings @dhairyaostwal 

Yes, you can go ahead and solve any famous problem and yes we will accept it in Java or any other language of your choice.

**Comment by SleepyAryan** [comment]
can i share the sorting algorithms like merge sort quick sort selection sort etc with comments

**Comment by dhairyaostwal** [comment]
> Greetings @dhairyaostwal
> 
> Yes, you can go ahead and solve any famous problem and yes we will accept it in Java or any other language of your choice.

Sure thanks! Good to close this issue from my end :)

**Comment by harshvardhan56** [comment]
kindly merge PR #41 
i have solved that problem using recursion

**Comment by harshvardhan56** [comment]
please merge PR #43 
solved using recursion

**Comment by harshvardhan56** [comment]
can i contribute in solve example by recursion repo??

**Comment by harshvardhan56** [comment]
please merge PR #49 
thankyou

**Comment by harshvardhan56** [comment]
can you please merge PR #62
